<script src="<?php if(isset($_SESSION['auth'])==1){echo "../";}?>assets/js/jquery-3.3.1.min.js"></script>
<script src="<?php if(isset($_SESSION['auth'])==1){echo "../";}?>assets/js/jquery-migrate-3.0.1.min.js"></script>
<script src="<?php if(isset($_SESSION['auth'])==1){echo "../";}?>assets/js/jquery-ui.js"></script>
<script src="<?php if(isset($_SESSION['auth'])==1){echo "../";}?>assets/js/popper.min.js"></script>
<script src="<?php if(isset($_SESSION['auth'])==1){echo "../";}?>assets/js/bootstrap.min.js"></script>
<script src="<?php if(isset($_SESSION['auth'])==1){echo "../";}?>assets/js/owl.carousel.min.js"></script>
<script src="<?php if(isset($_SESSION['auth'])==1){echo "../";}?>assets/js/jquery.stellar.min.js"></script>
<script src="<?php if(isset($_SESSION['auth'])==1){echo "../";}?>assets/js/jquery.countdown.min.js"></script>
<script src="<?php if(isset($_SESSION['auth'])==1){echo "../";}?>assets/js/bootstrap-datepicker.min.js"></script>
<script src="<?php if(isset($_SESSION['auth'])==1){echo "../";}?>assets/js/jquery.easing.1.3.js"></script>
<script src="<?php if(isset($_SESSION['auth'])==1){echo "../";}?>assets/js/aos.js"></script>
<script src="<?php if(isset($_SESSION['auth'])==1){echo "../";}?>assets/js/jquery.fancybox.min.js"></script>
<script src="<?php if(isset($_SESSION['auth'])==1){echo "../";}?>assets/js/jquery.sticky.js"></script>
<script src="<?php if(isset($_SESSION['auth'])==1){echo "../";}?>assets/js/jquery.mb.YTPlayer.min.js"></script>
<script src="<?php if(isset($_SESSION['auth'])==1){echo "../";}?>assets/js/main.js"></script>